### ISSUE TITLE
VAL$ not recognized

### ISSUE THREAD

**Issue by ryangray** [ohnosec/zmakebas#2]
The VAL$ token is not recognized properly, and gets turned into a "VAL" token followed by a "$". I think this is because the VAL token comes before VAL$ in the reversed token order.

I managed a fix by extending the existing check for PEEK/PEEK$ to look for PEEK or VAL followed by "$" on line 932 of zmakebas.c:

```
(!isalpha(ptr[-1]) && !isalpha(ptr[toklen]) && !( !zx81mode && ( toknum == PEEK_TOKEN_NUM || toknum == VAL_TOKEN_NUM) && ( ptr[toklen] == '$' )))		// :dbolli:20200420 18:54:45 Added check for PEEK that is actually PEEK$ (v1.5.2) // :ryangray:20221120 Added check for VAL that is actually VAL$
```

And, of course, adding a similar define near the top:

```
#define VAL_TOKEN_NUM       176                     // :ryangray:20221120 Added ZX Spectrum VAL token code
```

**Comment by ohnosec** [comment]
Thanks Ryan for both the issue and the fix :)
