### ISSUE TITLE
Ignore @ inside a string

### ISSUE THREAD

**Issue by patters-match** [ohnosec/zmakebas#5]
In label mode, zmakebas is interpreting characters after @ as a label definition even when they're inside a string, which it probably shouldn't do.
A workaround for this is to replace any instances of @ with ```\{64}```

**Comment by ohnosec** [comment]
The original author considered this a feature with this comment in the code.
```
/* replace @label with matching number.
* this expands labels in strings too, since:
* 1. it seems reasonable to assume you might want this;
* 2. it makes the code a bit simpler :-) ;
* 3. you can use the escape `\@' to get a literal `@' anyway.
*/
```
I can't see a use case for expanding a label in a string, but I don't want to break anyone that is relying on this feature. So I'm ok with adding a command line switch to make turn off this behavior if you want?

**Comment by patters-match** [comment]
I hadn't spotted that a literal '@' via ```\@``` is mentioned in **README.md**. I have updated [my own syntax highlighter](https://github.com/patters-syno/zx-basic-syntax) to take this into account. No change to zmakebas needed then - closing this issue.
